---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glossary
  namespace: glossary
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: glossary.nathanwhyte.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glossary
                port:
                  number: 4000
