---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glossary-storage
  namespace: glossary
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme
  resources:
    requests:
      storage: 10Gi

