---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hook-rollout-restart
  namespace: glossary
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hook-rollout-restart
  namespace: glossary
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hook-rollout-restart
subjects:
  - kind: ServiceAccount
    name: buildx-builder
    namespace: build
