---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glossary-config
  namespace: glossary
data:
  # Phoenix
  PORT: "4000"
  PHX_HOST: glossary.nathanwhyte.dev
  POOL_SIZE: "10"
  MIX_ENV: prod

  # Postgres
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "glossary"
